module.exports = [
    {
      id: 1,
      sender_id: 1,
      driver_id: 3,
      origin: 'Toronto',
      destination: 'Vaughan',
      date_posted: new Date(),
      job_date: new Date('December 17, 2022 03:24:00'),
      status: 'IN PROGRESS',
      payment_type: 'Sender',
      note: 'Leave at door',
      payment_amount: 10,
    },
    {
      id: 2,
      sender_id: 1,
      origin: 'Toronto',
      destination: 'Hamilton',
      date_posted: new Date(),
      job_date: new Date('December 12, 2022 03:24:00'),
      status: 'NEW',
      payment_type: 'Recipient',
      note: 'Leave at door',
      payment_amount: 20,
    },
    {
      id: 3,
      sender_id: 4,
      driver_id: 2,
      origin: 'Mississauga',
      destination: 'Barrie',
      date_posted: new Date(),
      job_date: new Date('November 30, 2022 03:24:00'),
      status: 'COMPLETED',
      payment_type: 'Sender',
      note: 'Leave at door',
      payment_amount: 30,
    },
    {
      id: 4,
      sender_id: 6,
      driver_id: 2,
      origin: 'Windsor',
      destination: 'Oshawa',
      date_posted: new Date(),
      job_date: new Date('January 25, 2022 06:15:00'),
      status: 'NEW',
      payment_type: 'Recipient',
      note: 'Leave at door',
      payment_amount: 72,
    },
];