module.exports = [
    {
      id: 1,
      sender_id: 1,
      driver_id: 3,
      origin: '70 Lennox St, Toronto, ON M6G 2P3',
      destination: '2525 Dunwin Dr, Mississauga, ON L5L 1R9',
      date_posted: new Date(),
      job_date: new Date('December 17, 2022 03:24:00'),
      status: 'IN PROGRESS',
      payment_type: 'Sender',
      note: 'Leave at door',
      payment_amount: 10,
    },
    {
      id: 2,
      sender_id: 1,
      origin: '151 Avenue Rd, Toronto, ON',
      destination: '49 Rutherford Rd S, Brampton, ON L6W 3J3',
      date_posted: new Date(),
      job_date: new Date('December 12, 2022 03:24:00'),
      status: 'NEW',
      payment_type: 'Recipient',
      note: 'Leave at door',
      payment_amount: 20,
    },
    {
      id: 3,
      sender_id: 4,
      driver_id: 2,
      origin: '1208 Winston Churchill Blvd, Mississauga, ON L5M 0N2',
      destination: '1559 Cataraqui St, Windsor, ON N9A 3R4',
      date_posted: new Date(),
      job_date: new Date('November 30, 2022 03:24:00'),
      status: 'COMPLETED',
      payment_type: 'Sender',
      note: 'Leave at door',
      payment_amount: 30,
    },
    {
      id: 4,
      sender_id: 6,
      driver_id: 2,
      origin: '3325 College Ave, Windsor, ON N9C 4E6',
      destination: '142 Gray St, Chatham, ON N7M 1T3',
      date_posted: new Date(),
      job_date: new Date('January 25, 2022 06:15:00'),
      status: 'NEW',
      payment_type: 'Recipient',
      note: 'Leave at door',
      payment_amount: 72,
    },
];